#ifndef SRC_INCLUDE_MPCAP_STREAM_EVENT_OBSERVER_H_
#define SRC_INCLUDE_MPCAP_STREAM_EVENT_OBSERVER_H_

#include <mpcap/stream/event/observer/interface.h>

#endif // SRC_INCLUDE_MPCAP_STREAM_EVENT_OBSERVER_H_
